CREATE TABLE "usuarios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "senha_hash" varchar NOT NULL,
  "tipo" varchar,
  "data_criacao" timestamp DEFAULT (now()),
  "ativo" boolean DEFAULT true
);

CREATE TABLE "clientes" (
  "usuario_id" integer PRIMARY KEY,
  "nome" varchar NOT NULL,
  "cpf" varchar UNIQUE NOT NULL,
  "telefone" varchar,
  "endereco" text,
  "data_nascimento" date
);

CREATE TABLE "funcionarios" (
  "usuario_id" integer PRIMARY KEY,
  "nome" varchar NOT NULL,
  "cpf" varchar UNIQUE NOT NULL,
  "telefone" varchar,
  "cargo" varchar NOT NULL,
  "especialidade" varchar
);

CREATE TABLE "veiculos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" integer,
  "modelo" varchar NOT NULL,
  "marca" varchar NOT NULL,
  "placa" varchar UNIQUE NOT NULL,
  "ano" varchar(4),
  "quilometragem" float,
  "quilometragem_media" float,
  "cor" varchar,
  "combustivel" varchar
);

CREATE TABLE "servicos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "veiculo_id" integer,
  "funcionario_id" integer,
  "promocao_id" integer,
  "descricao" text NOT NULL,
  "peca_id" integer,
  "status" varchar,
  "data_entrada" timestamp DEFAULT (now()),
  "data_saida" timestamp,
  "valor_mao_de_obra" decimal(10,2),
  "desconto_aplicado" decimal(10,2) DEFAULT 0,
  "valor_total" decimal(10,2),
  "observacoes" text
);

CREATE TABLE "pecas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "codigo" varchar UNIQUE,
  "fabricante" varchar,
  "preco_unitario" decimal(10,2) NOT NULL
);

CREATE TABLE "promocoes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar NOT NULL,
  "descricao" text,
  "data_inicio" timestamp NOT NULL,
  "data_fim" timestamp NOT NULL,
  "ativa" boolean DEFAULT true,
  "codigo_promocional" varchar NOT NULL,
  "desconto_percentual" decimal(5,2),
  "preco_promocional" decimal(10,2)
);

CREATE TABLE "manutencoes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "veiculo_id" integer,
  "cliente_id" integer,
  "tipo" varchar,
  "data_agendada" timestamp NOT NULL,
  "data_notificacao" timestamp,
  "confirmada" boolean DEFAULT false,
  "observacoes" text
);

CREATE TABLE "avaliacoes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" integer,
  "servico_id" integer,
  "nota" integer,
  "comentario" text,
  "data_avaliacao" timestamp DEFAULT (now()),
  "publicada" boolean DEFAULT false
);

CREATE TABLE "mensagens" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" integer,
  "funcionario_id" integer,
  "mensagem" text NOT NULL,
  "data_envio" timestamp DEFAULT (now()),
  "lida" boolean DEFAULT false,
  "resposta_para" integer,
  "assunto" varchar
);

CREATE TABLE "relatorios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "funcionario_id" integer,
  "tipo" varchar NOT NULL,
  "data_geracao" timestamp DEFAULT (now()),
  "parametros" jsonb,
  "periodo_inicio" timestamp,
  "periodo_fim" timestamp
);


